# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the main branch
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    # https://github.com/Apple-Actions/Example-iOS/blob/master/.github/workflows/test.yml
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # https://github.com/android-actions/setup-android
      - name: Setup Android SDK
        uses: FAIMS/setup-android@v2

      # https://docs.github.com/en/free-pro-team@latest/actions/guides/building-and-testing-java-with-gradle
      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}



      # https://github.com/oxr463/setup-cordova
      # This is a docker build, so I don't think any of the caching will do any good...
      # This is also using gradle 5.7 instead of 7, so we'll have to rebuild this.
      # - name: Use oxr463/setup-cordova
      #   uses: oxr463/setup-cordova@0.0.2
      #   with:
      #     exec: |
      #       cordova platform add android && \
      #       cordova build --no-telemetry && \
      #       echo "$(find . -name '*.apk')" && \
      #       cp "$(find . -name '*.apk')" .
      # https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows
      
      # https://github.com/marketplace/actions/setup-ionic
      # - name: Use coturiv/setup-ionic
      #   uses: coturiv/setup-ionic@v1
      #   with:
      #     cordova-version: 9

      # - name: Build
      #   run: |
      #     cordova platform add android
      #     cordova build --no-telemetry
      

      # https://cordova.apache.org/docs/en/latest/guide/cli/
      # We need to make sure to cache this, but ... later
      # - run: sudo npm install -g cordova # This installs cordova 10. We'll want to staple it to a specific major version.
      # - run: cordova platform add android # Again, adding that... locally. How odd.
      # - run: cordova requirements
      # - run: cordova build android 
      # limiting scope to only android here.
      # - run: sudo npm install -g cordova
      - run: npm install
      - run: npm run build
      # https://capacitorjs.com/docs/android
      - run: npx cap sync android
      # https://forum.ionicframework.com/t/how-to-build-apk-from-capacitor-ionic-poject-without-using-android-studio/177814/7
      - run: cd android && ./gradlew assembleDebug
      - run: cp "$(find . -name '*.apk')" .
      - name: Archive build
        uses: actions/upload-artifact@v2
        with:
          name: npm-build
          path: |
            build
      - name: Archive apks
        uses: actions/upload-artifact@v2
        with:
          name: apks
          path: |
            ./*.apk
      
